import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UserMenu from "@/components/UserMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white min-h-screen`}
        style={{ background: '#f8fafc' }}
      >
        <header className="w-full h-[72px] flex items-center justify-between px-8 bg-green-900 shadow-lg fixed top-0 left-0 z-50 border-b-4 border-yellow-400">
          <div className="text-2xl font-bold text-white tracking-tight drop-shadow flex items-center gap-2">
            DATI.IA
            <span className="ml-2 w-3 h-3 rounded-full bg-yellow-400 inline-block"></span>
          </div>
          <UserMenu />
        </header>
        <main className="w-full flex justify-center min-h-screen pt-[72px]">
          <div>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
